const USER_LOGIN = "USER_LOGIN";
const USER_REGISTER = "USER_REGISTER";
const RESTAURANT_LOGIN = "RESTAURANT_LOGIN";
const RESTAURANT_REGISTER = "RESTAURANT_REGISTER";
const LOGOUT = "LOGOUT";
const UNAUTHENTICATED = "UNAUTHENTICATED";
const UPDATE_USER = "UPDATE_USER";
const GET_CART = "GET_CART";
const EMPTY_CART = "EMPTY_CART";
const DELIVERY_MODE = "DELIVERY_MODE";

export {
  USER_LOGIN,
  USER_REGISTER,
  RESTAURANT_LOGIN,
  RESTAURANT_REGISTER,
  LOGOUT,
  UNAUTHENTICATED,
  UPDATE_USER,
  GET_CART,
  EMPTY_CART,
  DELIVERY_MODE,
};
