const USER_LOGIN = 'USER_LOGIN';
const USER_REGISTER = 'USER_REGISTER';
const RESTAURANT_LOGIN = 'RESTAURANT_LOGIN';
const RESTAURANT_REGISTER = 'RESTAURANT_REGISTER';
const LOGOUT = 'LOGOUT';
const UNAUTHENTICATED = 'UNAUTHENTICATED';

export {
    USER_LOGIN, USER_REGISTER, RESTAURANT_LOGIN, RESTAURANT_REGISTER, LOGOUT, UNAUTHENTICATED,
};